[phases.setup]
packages = ["python3", "python3-pip", "libpq-dev", "wkhtmltopdf"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = ""

[phases.start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
